### ISSUE TITLE
Entity id already exists since update to 0.1.7

### ISSUE THREAD

**Issue by u20p17** [delzear/hass-formulaoneapi#43]
Hi all,
I updated to the latest version of this repository and after restart I get the following error:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:658
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 07:02:35 (1 occurrences)
Last logged: 07:02:35

Entity id already exists - ignoring: sensor.formula_one_sensor_drivers
```

Before the update everything was working like expected. What can I do in order to fix the issue?

BR

**Comment by delzear** [comment]
I did not see this problem while updating but I have the same! I will look into this!

**Comment by DeadpoolW** [comment]
I think this is related, since the 0.1.7 update I get the following error in the log files as well:

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:515
First occurred: 7 October 2022 at 11:39:51 (1001 occurrences)
Last logged: 10:38:51

Update of sensor.formula_one_sensor_last_result is taking over 10 seconds
Update of binary_sensor.protection_window is taking over 10 seconds
Update of sensor.skin_type_4_safe_exposure_time is taking over 10 seconds
Update of sensor.formula_one_sensor_drivers is taking over 10 seconds
Update of sensor.skin_type_1_safe_exposure_time is taking over 10 seconds`

**Comment by brhahlen** [comment]
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:658
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 16:51:52 (1 occurrences)
Last logged: 16:51:52

Entity id already exists - ignoring: sensor.formula_one_sensor_drivers
```

Same problem here

**Comment by DeadpoolW** [comment]
Is it possible to revert to the 1.6.0? That one didn't had these issues

**Comment by marcokreeft87** [comment]
> Is it possible to revert to the 1.6.0? That one didn't had these issues

You can always go back to 1.6.0 on your HA. Just redownload the integration

**Comment by marcokreeft87** [comment]
I have found the issue. Update incoming
